config/routes.rb
Rails.application.routes.draw do
  root to: 'lists#index'
  resources :lists, only: [:index, :show, :new, :create, :destroy] do
    resources :bookmarks, only: [:new, :create]
  end
  resources :bookmarks, only: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list

  has_rich_text :rich_comment

  validates :comment, length: { minimum: 6 }
  validates_uniqueness_of :movie, scope: [:list]
end

app/models/list.rb
class List < ApplicationRecord
  has_many :bookmarks, dependent: :destroy
  has_many :movies, through: :bookmarks, dependent: :destroy

  validates :name, presence: true, uniqueness: true

  has_one_attached :photo
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks

  validates :title, presence: true, uniqueness: true
  validates :overview, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  def new
    @list = List.find(params[:list_id])
    @bookmark = Bookmark.new
  end

  def create
    @list = List.find(params[:list_id])
    @bookmark = Bookmark.new(bookmark_params)
    @bookmark.list = @list
    if @bookmark.save
      redirect_to list_path(@list)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @bookmark = Bookmark.find(params[:id])
    @bookmark.destroy
    redirect_to list_path(@bookmark.list), status: :see_other
  end

  private

  def bookmark_params
    params.require(:bookmark).permit(:comment, :movie_id)
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  def index
    @lists = List.all
    # @bookmarks = Bookmark.all
  end

  def show
    @list = List.find(params[:id])
    @bookmark = Bookmark.new
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)
    if @list.save
      redirect_to list_path(@list)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @list = List.find(params[:id])
    @list.destroy
    redirect_to lists_path, status: :see_other
  end

  private

  def list_params
    params.require(:list).permit(:name, :photo)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
  def get_url(list)
    if  list.photo.attached?
      cl_image_path(list.photo.key)
    elsif list.bookmarks.any?
       list.bookmarks.first.movie.poster_url
    else
      'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTPQDYau3Hs4-xw1i8jVSUY4BlF4FLmg8lQqg&usqp=CAU'
    end
  end
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/bookmarks/create.html.erb
<h1>Bookmarks#create</h1>
<p>Find me in app/views/bookmarks/create.html.erb</p>

app/views/bookmarks/new.html.erb
<div class="container">
  <div class="container col-sm-10 col-lg-8 bg-light p-3 mt-5 rounded">
    <h1 class="border-bottom p-3">Add Movie to <%= @list.name %></h1>
    <div class="container my-3">
      <%= simple_form_for([@list, @bookmark], html: {class: 'form-outline'}) do |f| %>
        <div class="mb-3">
          <%= f.association :movie, input_html: { class:'bg-light' } %>
        </div>
        <div class="mb-5">
          <%= f.rich_text_area :comment, input_html: { class:'bg-light' } %>
        </div>
        <%= f.submit :Submit, class: 'btn btn-primary' %>
      <% end %>
    </div>
  </div>
</div>

app/views/layouts/action_text/contents/_content.html.erb
<div class="trix-content">
  <%= yield -%>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Kyle's Rails WatchList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= favicon_link_tag asset_path('favicon.ico') %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>
  <body>
    <div class="navbar navbar-dark navbar-lewagon">
      <div class="container-fluid px-3">
        <%= link_to lists_path, class: "navbar-brand" do %>
          <%= image_tag "favicon.ico" %>
        <% end %>
        <%= link_to "WatchList", lists_path, class: "text-decoration-none text-light fs-3 fw-bold navbar-title" %>
        <div>
          <ul class="navbar-nav me-auto">
            <li class="nav-item dropdown">
              <%= image_tag "instapic-modified.png", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            </li>
          </ul>
        </div>
      </div>
    </div>
    <%= yield %>
  </body>
</html>

app/views/lists/create.html.erb
<h1>Lists#create</h1>
<p>Find me in app/views/lists/create.html.erb</p>

app/views/lists/index.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://images.unsplash.com/photo-1489599849927-2ee91cede3ba?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1470&q=80);">
  <div class="container">
    <h1>WatchList</h1>
    <p><span data-controller="typed-js"></span></p>
    <%= link_to "New List", new_list_path, class: "btn btn-primary" %>
  </div>
</div>
<div class="container my-3">
  <div class="cards">
    <% @lists.each do |list| %>
      <div class="item card-category shadow-lg" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(<%= get_url(list) %>)">
        <%= link_to list.name, list_path(list), class: "btn btn-dark" %>
      </div>
    <% end %>
  </div>
</div>

app/views/lists/new.html.erb
<div class="container">
  <div class="container col-sm-10 col-lg-8 bg-light p-3 mt-5 rounded">
    <h1 class="border-bottom p-3">Make a new list!</h1>
    <div class="container my-3 ">
      <%= simple_form_for(@list, html: {class: 'form-outline'}) do |f| %>
        <div class="mb-3">
          <%= f.input :name, input_html: { class:'bg-light' } %>
        </div>
        <div class="mb-5">
          <%= f.input :photo, as: :file, input_html: { class:'bg-light' } %>
        </div>
        <%= f.submit class: "btn btn-primary"%>
      <% end %>
    </div>
  </div>
</div>

app/views/lists/show.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(<%= @list.photo.attached? ? cl_image_path(@list.photo.key) : 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTPQDYau3Hs4-xw1i8jVSUY4BlF4FLmg8lQqg&usqp=CAU' %>);">
  <div class="container">
    <h1 class=""><%= @list.name %></h1>
    <%= link_to "Bookmark a Movie", new_list_bookmark_path(@list), class: "btn btn-primary" %>
  </div>
</div>
<div class="container my-3">
  <div class="cards">
    <% @list.bookmarks.each do |bookmark| %>
      <div class="card-category text-light" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(<%= bookmark.movie.poster_url %>)">
        <%= bookmark.movie.title %>
      </div>
    <% end %>
  </div>
  <div class="container my-3 d-flex justify-content-center">
    <%= link_to "Return To Lists", lists_path, class: "btn btn-light me-5" %>
    <%= link_to "Delete List", list_path(@list), data: { turbo_method: "delete", turbo_confirm: "Delete the #{@list.name} list?"}, class: "btn btn-danger" %>
  </div>
</div>